# Generated by Django 2.2.28 on 2023-11-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_character_equipement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='id_character',
            new_name='id',
        ),
    ]
